### Testar Rota Inicial
GET http://localhost:3000/

###

### Listar Filmes
GET http://localhost:3000/movies

###

### Criar Novo Filme
POST http://localhost:3000/movies
Content-Type: application/json

{
  "id": 5,
  "title": "O Senhor dos Anéis",
  "synopsis": "Testando",
  "genres": ["Comedia", "Drama"],
  "duration": 201,
  "url_movie": "teste"
}

###

### Atualizar Filme
PATCH http://localhost:3000/movies/O Senhor dos Anéis
Content-Type: application/json

{
  "duration": 300
}

###

### Deletar Filme
DELETE http://localhost:3000/movies/O Senhor dos Anéis

###

### Listar Playlists de um Usuário
GET http://localhost:3000/users/user-123/playlists

###



### Criar Nova Playlist
POST http://localhost:3000/playlists
Content-Type: application/json

{
  "name": "Maratonar nas férias",
  "userId": "user-123"
}

###

### Listar Playlists de um Usuário
GET http://localhost:3000/users/user-123/playlists

###

### Criar Playlist com Nome Repetido
POST http://localhost:3000/playlists
Content-Type: application/json

{
  "name": "Maratonar nas férias",
  "userId": "user-123"
}

###

### Criar Playlist sem Nome
POST http://localhost:3000/playlists
Content-Type: application/json

{
  "name": "",
  "userId": "user-123"
}

###

### Atualizar Nome da Playlist
PATCH http://localhost:3000/playlists/COLOQUE_AQUI_O_ID_DA_PLAYLIST
Content-Type: application/json

{
  "name": "Maratonar no feriadão"
}

###

### Deletar Playlist
DELETE http://localhost:3000/playlists/COLOQUE_AQUI_O_ID_DA_PLAYLIST